name: Setup Python and Install Dependencies
description: Setup Python and Install Dependencies

runs:
  using: 'composite'
  steps:
    - name: Install Just
      uses: extractions/setup-just@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: 'uv.lock'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --all-groups

    # - name: Install Sentry CLI
    #   shell: bash
    #   run: curl -sL https://sentry.io/get-cli/ | sh

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install Node Dependencies
      shell: bash
      run: npm ci
